n = input('Digite algo: ')
print(f'O tipo primitivo desse valor é : {type(n)}')
print(f'So tem espaços: {n.isspace()}')
print(f'É um número: {n.isnumeric()}')
print(f'É Alfabético: {n.isalpha()}')
print(f'É alfanúmerico: {n.isalnum()}')
print(f'Está em maiúsculas: {n.isupper()}')
print(f'Está em menpusculas: {n.islower()}')
print(f'Está capitalizada: {n.istitle()}')